### ISSUE TITLE
Using PortfolioService methods from epl statements 

### ISSUE THREAD

**Issue by shlominng** [espertechinc/esper#57] opened 2016-10-13 12:46 UTC
Hi 

I'm trying to use the following method inside an epl statement 
method: portfolioService.getNetLiqValueDouble()

The problem is that i get the following error - " Ambiguous method name: method by name 'getNetLiqValueDouble' is overloaded in class 'ch.algotrader.service.PortfolioService'  "

I did notice that there's an overloading on that method (one without parameters and one with a string) but i'm using the method without parameters and it does work within the java code (just not in the epl statement) 

Does anyone know the reason for that error  ?
 
Thanks in advance,
Shlomi

**Comment by bernhardttom** [comment] 2016-10-13 14:34
Provide a sample class please that reproduces this?

**Comment by shlominng** [comment] 2016-10-13 15:08
Hi 
I've added 2 attachments, the first one "MartinService "is the class who works properly and the other one " epl statement" is the one that trigger the error 
![class martinservice](https://cloud.githubusercontent.com/assets/22815930/19354563/e12c992e-916f-11e6-9da7-7601563a6dc9.PNG)
![epl statement](https://cloud.githubusercontent.com/assets/22815930/19354570/e87df8bc-916f-11e6-89c8-d11ce6c1c64e.PNG)


thank you for the quick respond,
Shlomi

**Comment by andyflury** [comment] 2016-10-14 08:36
The class PortfolioService has two methods with the same name but different signatures:

`
ch.algotrader.service.PortfolioService.getNetLiqValueDouble()
ch.algotrader.service.PortfolioService.getNetLiqValueDouble(String)
`

Looks like Esper cannot distinguish those two methods and throws:

`Ambiguous method name: method by name 'getNetLiqValueDouble' is overloaded in class 'ch.algotrader.service.PortfolioService'`

**Comment by shlominng** [comment] 2016-10-15 16:25
Hi

I notice that. 
Do you know a way to fix it and use portfolioService methods with esper ?

**Comment by bernhardttom** [comment] 2016-10-25 20:44
There as a change just merged that will be in version 6 that improves this behavior for overloaded methods.

**Closed by bernhardttom** 2016-10-25 20:44 UTC
